version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - appnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  service1:
    build: ./service_1
    expose:
      - "8001"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build: ./service_2
    expose:
      - "8002"
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  appnet:
    driver: bridge
